export const TRANSLATIONS = {
  en: {
    appTitle: "ResilientGuard",
    appSubtitle: "Citizen Disaster Early Warning & Area Safety",
    offlineNotice: "Showing cached data from 12:40 PM — reconnecting to local mesh...",
    coldStartNotice: "Limited local sensor telemetry — monitoring secondary satellite feeds closely",
    retrySync: "Retry Sync",
    dismiss: "Dismiss",
    navMyArea: "My Area",
    navMap: "Live Map",
    navAlerts: "Alerts",
    navReport: "Report Hazard",
    primaryReasonHeader: "Primary Factor",
    trendLineText: "Conditions stable over past 24h",
    freshnessText: "Updated 3 min ago",
    highConfidence: "Confidence: High (96%)",
    emergencyActionsHeader: "Emergency Support & Shelter",
    sosActive: "Active Alert",
    callEmergency112: "National Helpline 112",
    callDisasterControl: "Disaster Control 1077",
    shelterName: "Shillong Polo Ground Camp #1",
    shelterMeta: "0.8 km away • Capacity: 210/450 occupied • Medical Aid Ready",
    navigateShelter: "Route",
    telemetryRainfall: "Rainfall Intensity",
    telemetrySoil: "Soil Saturation",
    telemetrySlope: "Ground Deformation",
    savedRoutesHeader: "Saved Commute Corridor",
    viewOnMap: "View on Map →",
    homeRouteTitle: "GS Road Urban Corridor",
    homeRouteSub: "Shillong Arterial Route • 12.4 km",
    blockedBadge: "Blocked (Urban Slopes)",
    openBadge: "Open & Clear",
    corridorNoticeHeader: "Corridor Status",
    advisoryHeader: "Safeguard Rules",
    advisory1: "Keep emergency kit & essential IDs ready.",
    advisory2: "Avoid steep slopes and swollen stream beds.",
    advisory3: "Check Live Map road status before travel.",
    advisory4: "Report new ground cracks or blockages instantly.",
    legendOpen: "Open",
    legendAtRisk: "At-Risk",
    legendBlocked: "Blocked",
    legendShelter: "Shelter",
    mapInspectorHeader: "Geospatial Inspector",
    monitoredRoadsHeader: "Monitored Corridors",
    sheltersHeader: "Designated Shelters",
    alertsPageTitle: "Active Alerts & Corridors",
    alertsPageSub: "Real-time hazard notifications based on telemetry fusion",
    filterAll: "All Alerts",
    filterArea: "My Area",
    filterRoute: "Saved Routes",
    alertScopeArea: "Area Hazard Alert",
    alert1Headline: "High Landslide Probability: Shillong Ridge Slopes",
    alert1Desc: "Satellite InSAR ground analysis registered displacement acceleration following continuous 52 mm/h precipitation. Residents along urban ridge slopes are advised to proceed to designated relief shelters.",
    dataSourceLine1: "Based on Rainfall Radar + Earth Engine Satellite Imagery + InSAR Telemetry",
    alertScopeRoute: "Saved Route Disruption",
    alert2Headline: "GS Road Corridor Blockage (Shillong-Guwahati Link)",
    alert2Desc: "Slope debris and runoff have closed both lanes near Shillong urban ridge. Road clearing teams actively deployed.",
    alternateAvailableHeader: "Alternate Road Available: Shillong Peak Link Bypass",
    alternateRouteSub: "Paved two-lane road • Safe elevation • +15 mins transit time",
    applyAlternateRoute: "Use Alternate Route",
    dataSourceLine2: "Based on Traffic Police Feeds + Highway Telemetry + Satellite Radar",
    emptyAlertsTitle: "No Active Warnings or Route Blockages",
    emptyAlertsDesc: "All monitored regions, precipitation zones, and commuter corridors in your sector are operating within normal safety limits.",
    reportTitle: "Report Ground & Road Hazard",
    reportSubtitle: "Field observations assist early-warning models and verify localized safety statuses.",
    reportPhotoLabel: "Photo Evidence",
    optionalTag: "Visual verification",
    uploadDirectTitle: "Direct Photo Upload",
    uploadDirectSub: "Select photos from device gallery / storage",
    geotagCamTitle: "Open Geotag Camera",
    geotagCamSub: "Instant photo with real-time GPS & timestamp",
    uploadPromptTitle: "Tap to Upload Hazard Photo",
    uploadPromptSub: "Supports JPG, PNG with auto-geotagging",
    reportLocationLabel: "Hazard Location",
    autoDetectedTag: "Auto-filled GPS",
    btnDetectGPS: "Detect GPS",
    reportHazardTypeLabel: "Select Issue Category",
    singleSelectTag: "Tap to select",
    tagCrack: "Ground / Wall Crack",
    tagWater: "Water Logging / Inundation",
    tagRoadBlocked: "Road Blocked",
    tagMovement: "Landslide / Slope Movement",
    tagBridge: "Bridge / Culvert Damage",
    tagWires: "Fallen Utilities / Poles",
    reportDescLabel: "Additional Remarks",
    btnSubmitOnline: "Submit Citizen Hazard Report",
    btnSubmitOffline: "Save to Offline Queue (Syncs when online)",
    modalConfirmTitle: "Report Dispatched Successfully",
    modalConfirmSub: "Your observation has been registered in the early warning system and routed to the control center.",
    confirmRefId: "Reference ID:",
    confirmStatus: "Status:",
    confirmLocation: "Location:",
    confirmCategory: "Category:",
    modalClose: "Close & Return"
  },
  hi: {
    appTitle: "रेजिलिएंटगार्ड",
    appSubtitle: "नागरिक आपदा पूर्व चेतावनी एवं क्षेत्र सुरक्षा",
    offlineNotice: "दोपहर 12:40 का कैश्ड डेटा प्रदर्शित — स्थानीय नेटवर्क से पुनः जुड़ रहा है...",
    coldStartNotice: "सीमित स्थानीय सेंसर डेटा — द्वितीयक उपग्रह फ़ीड की निगरानी की जा रही है",
    retrySync: "पुनः प्रयास करें",
    dismiss: "हटाएं",
    navMyArea: "मेरा क्षेत्र",
    navMap: "लाइव मैप",
    navAlerts: "अलर्ट",
    navReport: "जोखिम रिपोर्ट",
    primaryReasonHeader: "मुख्य कारक",
    trendLineText: "पिछले 24 घंटों में स्थितियां स्थिर",
    freshnessText: "3 मिनट पहले अपडेट",
    highConfidence: "सटीकता: उच्च (96%)",
    emergencyActionsHeader: "आपातकालीन सहायता एवं आश्रय",
    sosActive: "सक्रिय चेतावनी",
    callEmergency112: "राष्ट्रीय हेल्पलाइन 112",
    callDisasterControl: "नियंत्रण कक्ष 1077",
    shelterName: "शिलांग पोलो ग्राउंड राहत केंद्र #1",
    shelterMeta: "0.8 किमी दूर • क्षमता: 210/450 भरी हुई • चिकित्सा सुविधा उपलब्ध",
    navigateShelter: "मार्ग",
    telemetryRainfall: "वर्षा तीव्रता",
    telemetrySoil: "मिट्टी की नमी",
    telemetrySlope: "भू-विस्थापन (उपग्रह)",
    savedRoutesHeader: "सहेजा गया आवागमन मार्ग",
    viewOnMap: "मानचित्र पर देखें →",
    homeRouteTitle: "जीएस रोड शहरी मार्ग",
    homeRouteSub: "शिलांग मुख्य मार्ग • 12.4 किमी",
    blockedBadge: "अवरुद्ध (शहरी ढलान)",
    openBadge: "खुला एवं सुरक्षित",
    corridorNoticeHeader: "मार्ग की स्थिति",
    advisoryHeader: "सुरक्षा नियम (सेफगार्ड)",
    advisory1: "आपातकालीन किट व पहचान पत्र तैयार रखें।",
    advisory2: "खड़ी ढलानों और जलधाराओं से दूर रहें।",
    advisory3: "यात्रा से पहले लाइव मैप पर मार्ग जांचें।",
    advisory4: "जमीनी दरारों की तुरंत रिपोर्ट करें।",
    legendOpen: "खुला है",
    legendAtRisk: "जोखिम में",
    legendBlocked: "अवरुद्ध",
    legendShelter: "राहत केंद्र",
    mapInspectorHeader: "भौगोलिक विश्लेषक",
    monitoredRoadsHeader: "निगरानी वाले मार्ग",
    sheltersHeader: "निर्धारित राहत केंद्र",
    alertsPageTitle: "सक्रिय अलर्ट एवं आवागमन मार्ग",
    alertsPageSub: "सेंसर डेटा पर आधारित वास्तविक समय चेतावनी",
    filterAll: "सभी अलर्ट",
    filterArea: "मेरा क्षेत्र",
    filterRoute: "सहेजे गए मार्ग",
    alertScopeArea: "क्षेत्रीय आपदा अलर्ट",
    alert1Headline: "भूस्खलन की अत्यधिक संभावना: शिलांग कटक ढलान",
    alert1Desc: "लगातार 52 मिमी/घंटा बारिश के बाद उपग्रह इनसार विश्लेषण ने विस्थापन दर्ज किया। ढलान के निवासियों को राहत केंद्र जाने की सलाह दी जाती है।",
    dataSourceLine1: "वर्षा रडार + अर्थ इंजन उपग्रह चित्र + इनसार टेलीमेट्री पर आधारित",
    alertScopeRoute: "सहेजे गए मार्ग में बाधा",
    alert2Headline: "जीएस रोड पर सड़क अवरुद्ध (शिलांग-गुवाहाटी लिंक)",
    alert2Desc: "मलबे और भू-कटाव के कारण जीएस रोड का मुख्य भाग बंद है। सड़क निकासी मशीनें तैनात हैं।",
    alternateAvailableHeader: "वैकल्पिक मार्ग उपलब्ध: शिलांग पीक लिंक बाईपास",
    alternateRouteSub: "पक्की दो-लेन सड़क • सुरक्षित ऊंचाई • +15 मिनट का समय",
    applyAlternateRoute: "वैकल्पिक मार्ग चुनें",
    dataSourceLine2: "यातायात पुलिस + राजमार्ग डेटा + उपग्रह रडार पर आधारित",
    emptyAlertsTitle: "कोई सक्रिय चेतावनी या सड़क अवरोध नहीं",
    emptyAlertsDesc: "आपके क्षेत्र में सभी उपग्रह अवलोकित क्षेत्र, वर्षा क्षेत्र और मार्ग सामान्य सुरक्षा सीमा में काम कर रहे हैं।",
    reportTitle: "जमीनी व सड़क जोखिम दर्ज करें",
    reportSubtitle: "नागरिक अवलोकन पूर्व चेतावनी मॉडल को सटीक बनाने में मदद करते हैं।",
    reportPhotoLabel: "फ़ोटो प्रमाण",
    optionalTag: "वैकल्पिक",
    uploadDirectTitle: "सीधा फोटो अपलोड",
    uploadDirectSub: "गैलरी या स्टोरेज से फोटो चुनें",
    geotagCamTitle: "जियोटैग कैमरा खोलें",
    geotagCamSub: "लाइव जीपीएस और टाइमस्टैम्प के साथ फोटो लें",
    uploadPromptTitle: "जोखिम की तस्वीर अपलोड करें",
    uploadPromptSub: "स्वतः स्थान टैगिंग के साथ जेपीजी, पीएनजी समर्थित",
    reportLocationLabel: "जोखिम का स्थान",
    autoDetectedTag: "स्वतः जीपीएस",
    btnDetectGPS: "जीपीएस प्राप्त करें",
    reportHazardTypeLabel: "समस्या की श्रेणी चुनें",
    singleSelectTag: "चुनने के लिए टैप करें",
    tagCrack: "जमीन / दीवार में दरार",
    tagWater: "जलभराव / बाढ़",
    tagRoadBlocked: "सड़क अवरुद्ध",
    tagMovement: "भूस्खलन / मिट्टी का खिसकना",
    tagBridge: "पुल / पुलिया की क्षति",
    tagWires: "गिरे हुए बिजली के खंभे/तार",
    reportDescLabel: "अतिरिक्त विवरण",
    btnSubmitOnline: "नागरिक रिपोर्ट जमा करें",
    btnSubmitOffline: "ऑफ़लाइन कतार में सहेजें (ऑनलाइन आने पर सिंक होगा)",
    modalConfirmTitle: "रिपोर्ट सफलतापूर्वक भेजी गई",
    modalConfirmSub: "आपकी जानकारी पूर्व चेतावनी प्रणाली में दर्ज कर नियंत्रण केंद्र को भेज दी गई है।",
    confirmRefId: "संदर्भ संख्या:",
    confirmStatus: "स्थिति:",
    confirmLocation: "स्थान:",
    confirmCategory: "श्रेणी:",
    modalClose: "बंद करें और वापस जाएं"
  }
};

export const RISK_DATA = {
  safe: {
    level: "SAFE",
    levelHi: "सुरक्षित",
    color: "#059669",
    bgColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    reasonEn: "Rainfall, terrain slope data, and satellite-derived soil wetness for this sector are within normal safety thresholds. No unusual land movement detected in recent observations.",
    reasonHi: "इस क्षेत्र के लिए वर्षा, ढलान डेटा और उपग्रह आधारित मिट्टी की नमी सामान्य सुरक्षा सीमा में हैं। हालिया अवलोकनों में कोई असामान्य हलचल दर्ज नहीं की गई।",
    trendEn: "Conditions stable over past 24h",
    trendHi: "पिछले 24 घंटों में स्थितियां स्थिर",
    rainfall: "2 mm/h",
    rainfallStat: "Normal Light",
    rainfallColor: "#059669",
    soil: "38%",
    soilStat: "Normal Dry",
    soilColor: "#059669",
    slope: "0.1 mm/h",
    slopeStat: "No movement detected (satellite)",
    slopeColor: "#059669",
    badgeClass: "safe",
    gaugeAngle: 45
  },
  watch: {
    level: "WATCH",
    levelHi: "सतर्कता",
    color: "#d97706",
    bgColor: "#fffbeb",
    borderColor: "#fde68a",
    reasonEn: "Satellite and weather radar indicate persistent light rainfall; slight soil wetness increase detected in Sector 2.",
    reasonHi: "उपग्रह और मौसम रडार लगातार हल्की वर्षा दर्शा रहे हैं; सेक्टर 2 में मिट्टी की नमी में मामूली वृद्धि दर्ज।",
    trendEn: "Gradual moisture increase over past 12h",
    trendHi: "पिछले 12 घंटों में नमी में क्रमिक वृद्धि",
    rainfall: "14 mm/h",
    rainfallStat: "Moderate Drizzle",
    rainfallColor: "#d97706",
    soil: "62%",
    soilStat: "Elevated Saturation",
    soilColor: "#d97706",
    slope: "0.8 mm/h",
    slopeStat: "Minor displacement noted (satellite)",
    slopeColor: "#d97706",
    badgeClass: "watch",
    gaugeAngle: 120
  },
  warning: {
    level: "WARNING",
    levelHi: "चेतावनी",
    color: "#ea580c",
    bgColor: "#fff7ed",
    borderColor: "#fed7aa",
    reasonEn: "Heavy rainfall detected on Doppler radar; satellite moisture models show elevated soil saturation on steep terrain.",
    reasonHi: "डॉपलर रडार पर भारी वर्षा दर्ज; उपग्रह नमी मॉडल खड़ी ढलानों पर बढ़ी हुई मिट्टी की नमी दर्शा रहे हैं।",
    trendEn: "Rapid runoff accumulation over past 6h",
    trendHi: "पिछले 6 घंटों में तेजी से जल संचय",
    rainfall: "32 mm/h",
    rainfallStat: "Heavy Downpour",
    rainfallColor: "#ea580c",
    soil: "78%",
    soilStat: "High Moisture",
    soilColor: "#ea580c",
    slope: "2.1 mm/h",
    slopeStat: "Elevated surface shift (satellite)",
    slopeColor: "#ea580c",
    badgeClass: "warning",
    gaugeAngle: 195
  },
  danger: {
    level: "DANGER",
    levelHi: "खतरा",
    color: "#dc2626",
    bgColor: "#fef2f2",
    borderColor: "#fecaca",
    reasonEn: "Heavy upstream precipitation and satellite InSAR analysis indicate accelerated ground movement along western ridge.",
    reasonHi: "भारी वर्षा और उपग्रह इनसार विश्लेषण पश्चिमी कटक पर तीव्र सतही विस्थापन दर्शाते हैं।",
    trendEn: "Significant displacement acceleration in past 3h",
    trendHi: "पिछले 3 घंटों में तेजी से विस्थापन",
    rainfall: "48 mm/h",
    rainfallStat: "Heavy Downpour",
    rainfallColor: "#dc2626",
    soil: "89%",
    soilStat: "Critical Moisture",
    soilColor: "#dc2626",
    slope: "4.2 mm/h",
    slopeStat: "Active movement detected (satellite)",
    slopeColor: "#dc2626",
    badgeClass: "danger",
    gaugeAngle: 280
  }
};

export const ROADS_DATA = [
  {
    id: "shillong-corridor",
    name: "GS Road Urban Corridor (Shillong)",
    status: "Blocked",
    badgeClass: "blocked",
    transitStatus: "Closed for Transit",
    advisory: "Use Bypass (+15m)",
    description: "Slope mudflow and high runoff have closed both lanes of GS Road near Shillong urban ridge. Road clearing teams actively deployed.",
    locationMeta: "Shillong • GS Road Ridge",
    center: [25.5750, 91.8900],
    coords: [
      [25.5680, 91.8820],
      [25.5700, 91.8845],
      [25.5720, 91.8870],
      [25.5740, 91.8890],
      [25.5760, 91.8915],
      [25.5780, 91.8940],
      [25.5800, 91.8965]
    ],
    alternateRoute: {
      name: "Shillong Peak Link Bypass",
      status: "Open",
      distance: "12.4 km",
      extraTime: "+15 mins",
      notes: "Reinforced ridge bypass away from active slope drainage channels",
      coords: [
        [25.5680, 91.8820],
        [25.5660, 91.8850],
        [25.5650, 91.8890],
        [25.5670, 91.8930],
        [25.5710, 91.8960],
        [25.5760, 91.8980],
        [25.5800, 91.8965]
      ]
    }
  },
  {
    id: "cherrapunji-road",
    name: "Cherrapunji (Sohra) Escarpment Road",
    status: "Blocked",
    badgeClass: "blocked",
    transitStatus: "Critical Blockage",
    advisory: "Use Ridge Transit",
    description: "Heavy escarpment sheetwash and debris fall along Sohra gorge. Transit halted for all vehicles.",
    locationMeta: "Cherrapunji • Sohra Escarpment",
    center: [25.2680, 91.7280],
    coords: [
      [25.2600, 91.7200],
      [25.2640, 91.7240],
      [25.2680, 91.7280],
      [25.2720, 91.7320],
      [25.2760, 91.7360]
    ],
    alternateRoute: {
      name: "Nohkalikai Ridge Transit Route",
      status: "Open",
      distance: "9.8 km",
      extraTime: "+20 mins",
      notes: "Elevated bedrock ridge transit clear of drainage gullies",
      coords: [
        [25.2600, 91.7200],
        [25.2620, 91.7250],
        [25.2660, 91.7290],
        [25.2700, 91.7340],
        [25.2760, 91.7360]
      ]
    }
  },
  {
    id: "trans-arunachal",
    name: "Trans-Arunachal Sector (NH-13)",
    status: "At-Risk",
    badgeClass: "at-risk",
    transitStatus: "Single-Lane Escort",
    advisory: "Drive with Care",
    description: "Saturated slope coluvium causing loose boulder fall. Single lane open under police convoy.",
    locationMeta: "Arunachal • Remote Valley NH-13",
    center: [28.6480, 96.1480],
    coords: [
      [28.6400, 96.1400],
      [28.6440, 96.1440],
      [28.6480, 96.1480],
      [28.6520, 96.1520],
      [28.6560, 96.1560]
    ],
    alternateRoute: {
      name: "Valley Low Bypass Route",
      status: "Open",
      distance: "18.5 km",
      extraTime: "+25 mins",
      notes: "Lower flood plain embankment bypass route",
      coords: [
        [28.6400, 96.1400],
        [28.6430, 96.1450],
        [28.6470, 96.1500],
        [28.6510, 96.1540],
        [28.6560, 96.1560]
      ]
    }
  },
  {
    id: "shillong-bypass",
    name: "Shillong Bypass Highway (NH-6)",
    status: "Open",
    badgeClass: "open",
    transitStatus: "Open & Clear",
    advisory: "Safe for All Traffic",
    description: "National Highway corridor fully open and monitored with live slope sensors.",
    locationMeta: "Shillong • NH-6 Bypass",
    center: [25.5900, 91.9100],
    coords: [
      [25.5800, 91.9000],
      [25.5850, 91.9050],
      [25.5900, 91.9100],
      [25.5950, 91.9150]
    ],
    alternateRoute: null
  }
];

export const LOCATIONS_DATA = [
  {
    id: "shillong",
    name: "Shillong Urban Ridge, Meghalaya",
    title: "Shillong — Urban & Ridge Slopes",
    subtitle: "Meghalaya • Live Earth Engine Feeds",
    lat: 25.5788,
    lng: 91.8933,
    risk: "danger",
    telemetry: {
      rainfall: "48 mm/h",
      rainfallStat: "Heavy Downpour",
      soil: "89%",
      soilStat: "Critical Moisture",
      slope: "4.2 mm/h",
      slopeStat: "Active movement detected (satellite)"
    }
  },
  {
    id: "cherrapunji",
    name: "Cherrapunji (Sohra) Escarpment, Meghalaya",
    title: "Cherrapunji — Sohra Escarpment & Gorges",
    subtitle: "Meghalaya • High Precipitation Radar Zone",
    lat: 25.2700,
    lng: 91.7300,
    risk: "warning",
    telemetry: {
      rainfall: "32 mm/h",
      rainfallStat: "Heavy Downpour",
      soil: "78%",
      soilStat: "High Moisture",
      slope: "2.1 mm/h",
      slopeStat: "Elevated surface shift (satellite)"
    }
  },
  {
    id: "arunachal",
    name: "Anjaw / Lohit Border Sector, Arunachal Pradesh",
    title: "Remote Mountain Slopes — Arunachal Pradesh",
    subtitle: "Eastern Himalaya • InSAR Monitored Corridor",
    lat: 28.6500,
    lng: 96.1500,
    risk: "watch",
    telemetry: {
      rainfall: "14 mm/h",
      rainfallStat: "Moderate Drizzle",
      soil: "62%",
      soilStat: "Elevated Saturation",
      slope: "0.8 mm/h",
      slopeStat: "Minor displacement noted (satellite)"
    }
  },
  {
    id: "guwahati",
    name: "Guwahati Valley Foothills, Assam",
    title: "Guwahati — Valley Slopes & Lowlands",
    subtitle: "Assam • Urban Drainage & Weather Radar",
    lat: 26.1445,
    lng: 91.7362,
    risk: "safe",
    telemetry: {
      rainfall: "2 mm/h",
      rainfallStat: "Normal Light",
      soil: "38%",
      soilStat: "Normal Dry",
      slope: "0.1 mm/h",
      slopeStat: "No movement detected (satellite)"
    }
  }
];

export const SHELTERS_DATA = [
  {
    name: "Shillong Polo Ground Camp #1",
    lat: 25.5840,
    lng: 91.8950,
    capacity: "210 / 450 Occupied",
    supplies: "Medical Tent, Emergency Power, Clean Water",
    distance: "0.8 km"
  },
  {
    name: "Mawlai Higher Secondary Relief Zone",
    lat: 25.5890,
    lng: 91.8790,
    capacity: "85 / 300 Occupied",
    supplies: "SDRF First Aid, Wireless Ham Radio",
    distance: "1.6 km"
  },
  {
    name: "St. Anthony Relief Safe Ground",
    lat: 25.5690,
    lng: 91.8980,
    capacity: "140 / 500 Occupied",
    supplies: "Community Kitchen, Satellite Comm Hub",
    distance: "2.1 km"
  }
];
